SurveyManagemnet/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from survey import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^survey/', include('survey.urls')),




]

survey/urls.py
from . import views
from django.conf.urls import url


# SET THE NAMESPACE!
app_name = 'survey'
# Be careful setting the name to just /login use userlogin instead!

urlpatterns = [

    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^login/$', views.login, name='login'),
    url(r'^survey_detail/$', views.EmployeeSurveys.as_view(), name='survey_detail'),

]

survey/forms.py
# -*- coding: utf-8 -*-

import logging
import uuid

from django import forms
from django.forms import models
from django.urls import reverse
from django.utils.text import slugify

from .models import Answer, Question, Response
from .signals import survey_completed


LOGGER = logging.getLogger(__name__)


class ResponseForm(models.ModelForm):

    WIDGETS = {
        Question.TEXT: forms.Textarea,
        Question.SHORT_TEXT: forms.TextInput,
        Question.RADIO: forms.RadioSelect,
        Question.SELECT: forms.Select,
        Question.SELECT_MULTIPLE: forms.CheckboxSelectMultiple,
    }

    class Meta(object):
        model = Response
        fields = ()

    def __init__(self, *args, **kwargs):
        """ Expects a survey object to be passed in initially """
        self.survey = kwargs.pop("survey")
        self.user = kwargs.pop("user")
        try:
            self.step = int(kwargs.pop("step"))
        except KeyError:
            self.step = None
        super(ResponseForm, self).__init__(*args, **kwargs)
        self.uuid = uuid.uuid4().hex
        self.steps_count = len(self.survey.questions.all())
        # add a field for each survey question, corresponding to the question
        # type as appropriate.
        data = kwargs.get("data")
        for i, question in enumerate(self.survey.questions.all()):
            is_current_step = i != self.step and self.step is not None
            if self.survey.display_by_question and is_current_step:
                continue
            else:
                self.add_question(question, data)

    def _get_preexisting_response(self):
        """ Recover a pre-existing response in database.

        The user must be logged.
        :rtype: Response or None"""
        if not self.user.is_authenticated:
            return None
        try:
            return Response.objects.get(user=self.user, survey=self.survey)
        except Response.DoesNotExist:
            LOGGER.debug(
                "No saved response for '%s' for user %s", self.survey, self.user
            )
            return None

    def _get_preexisting_answer(self, question):
        """ Recover a pre-existing answer in database.

        The user must be logged. A Response containing the Answer must exists.

        :param Question question: The question we want to recover in the
        response.
        :rtype: Answer or None"""
        response = self._get_preexisting_response()
        if response is None:
            return None
        try:
            return Answer.objects.get(question=question, response=response)
        except Answer.DoesNotExist:
            return None

    def get_question_initial(self, question, data):
        """ Get the initial value that we should use in the Form

        :param Question question: The question
        :param dict data: Value from a POST request.
        :rtype: String or None  """
        initial = None
        answer = self._get_preexisting_answer(question)
        if answer:
            # Initialize the field with values from the database if any
            if question.type == Question.SELECT_MULTIPLE:
                initial = []
                if answer.body == "[]":
                    pass
                elif "[" in answer.body and "]" in answer.body:
                    initial = []
                    unformated_choices = answer.body[1:-1].strip()
                    for unformated_choice in unformated_choices.split(","):
                        choice = unformated_choice.split("'")[1]
                        initial.append(slugify(choice))
                else:
                    # Only one element
                    initial.append(slugify(answer.body))
            else:
                initial = answer.body
        if data:
            # Initialize the field field from a POST request, if any.
            # Replace values from the database
            initial = data.get("question_%d" % question.pk)
        return initial

    def get_question_widget(self, question):
        """ Return the widget we should use for a question.

        :param Question question: The question
        :rtype: django.forms.widget or None """
        try:
            return self.WIDGETS[question.type]
        except KeyError:
            return None

    def get_question_choices(self, question):
        """ Return the choices we should use for a question.

        :param Question question: The question
        :rtype: List of String or None """
        qchoices = None
        if question.type not in [Question.TEXT, Question.SHORT_TEXT, Question.INTEGER]:
            qchoices = question.get_choices()
            # add an empty option at the top so that the user has to explicitly
            # select one of the options
            if question.type in [Question.SELECT, Question.SELECT_IMAGE]:
                qchoices = tuple([("", "-------------")]) + qchoices
        return qchoices

    def get_question_field(self, question, **kwargs):
        """ Return the field we should use in our form.

        :param Question question: The question
        :param **kwargs: A dict of parameter properly initialized in
            add_question.
        :rtype: django.forms.fields """
        FIELDS = {
            Question.TEXT: forms.CharField,
            Question.SHORT_TEXT: forms.CharField,
            Question.SELECT_MULTIPLE: forms.MultipleChoiceField,
            Question.INTEGER: forms.IntegerField,
        }
        # logging.debug("Args passed to field %s", kwargs)
        try:
            return FIELDS[question.type](**kwargs)
        except KeyError:
            return forms.ChoiceField(**kwargs)

    def add_question(self, question, data):
        """ Add a question to the form.

        :param Question question: The question to add.
        :param dict data: The pre-existing values from a post request. """
        kwargs = {"label": question.text, "required": question.required}
        initial = self.get_question_initial(question, data)
        if initial:
            kwargs["initial"] = initial
        choices = self.get_question_choices(question)
        if choices:
            kwargs["choices"] = choices
        widget = self.get_question_widget(question)
        if widget:
            kwargs["widget"] = widget
        field = self.get_question_field(question, **kwargs)
        if question.category:
            field.widget.attrs["category"] = question.category.name
        else:
            field.widget.attrs["category"] = ""
        # logging.debug("Field for %s : %s", question, field.__dict__)
        self.fields["question_%d" % question.pk] = field

    def has_next_step(self):
        if self.survey.display_by_question:
            if self.step < self.steps_count - 1:
                return True
        return False

    def next_step_url(self):
        if self.has_next_step():
            context = {"id": self.survey.id, "step": self.step + 1}
            return reverse("survey-detail-step", kwargs=context)
        else:
            return None

    def current_step_url(self):
        return reverse(
            "survey-detail-step", kwargs={"id": self.survey.id, "step": self.step}
        )

    def save(self, commit=True):
        """ Save the response object """
        # Recover an existing response from the database if any
        #  There is only one response by logged user.
        response = self._get_preexisting_response()
        if response is None:
            response = super(ResponseForm, self).save(commit=False)
        response.survey = self.survey
        response.interview_uuid = self.uuid
        if self.user.is_authenticated:
            response.user = self.user
        response.save()
        # response "raw" data as dict (for signal)
        data = {
            "survey_id": response.survey.id,
            "interview_uuid": response.interview_uuid,
            "responses": [],
        }
        # create an answer object for each question and associate it with this
        # response.
        for field_name, field_value in list(self.cleaned_data.items()):
            if field_name.startswith("question_"):
                # warning: this way of extracting the id is very fragile and
                # entirely dependent on the way the question_id is encoded in
                # the field name in the __init__ method of this form class.
                q_id = int(field_name.split("_")[1])
                question = Question.objects.get(pk=q_id)
                answer = self._get_preexisting_answer(question)
                if answer is None:
                    answer = Answer(question=question)
                if question.type == Question.SELECT_IMAGE:
                    value, img_src = field_value.split(":", 1)
                    # TODO
                answer.body = field_value
                data["responses"].append((answer.question.id, answer.body))
                LOGGER.debug(
                    "Creating answer for question %d of type %s : %s",
                    q_id,
                    answer.question.type,
                    field_value,
                )
                answer.response = response
                answer.save()
        survey_completed.send(sender=Response, instance=response, data=data)
        return response

survey/views.py
from django.shortcuts import render, render_to_response
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import login as auth_login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, TemplateView, ListView, DetailView
from survey import models


# Create your views here.

def index(request):
    return render(request, 'survey/home.html')


def login(request):
    return render(request, 'survey/login.html')


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                auth_login(request, user)
                return render(request, 'survey/survey_home.html', {})
            else:
                return HttpResponse("Your account was inactive.")
        else:
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'survey/login.html', {})


class EmployeeSurveys(LoginRequiredMixin, ListView):
    context_object_name = 'UsersSurveys'
    model = models.UsersSurveys
    template_name = 'survey/survey_home.html'

    def get_queryset(user):
        return models.objects.filter(user=user.request.user)

templates/survey/UsersSurveyAssignment.html
{% extends "survey/base.html" %}
{% block body_block %}
<div class="container">
  <div class="jumbotron">
    <h2>Welcome to the Employee Survey System !</h2>
    {% if user.is_superuser %}
        <h2>Assign Survey to Users</h2>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_survey_form.as_p }}
          <input type="submit" name="" value="Assign">
        </form>
    {% else %}
        <h2>You are not authorised person for assignment</h2>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/survey/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- Le styles -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>
<body>



<div class="container">
    {% block body_block %}
    {% endblock %}
</div>
<!-- Le javascript -->
<link rel="stylesheet" href="{% static 'css/flick/jquery-ui-1.9.1.custom.css' %}"/>
<script src="{% static 'js/jquery-1.8.2.js' %}"></script>
<script src="{% static 'js/jquery-ui-1.9.1.custom.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script>
		// use the jquery UI datepicker on all pages with the datepicker class:
		$(".datepicker").datepicker({ minDate: 0});
		  $('.readonly').find('input, textarea, select').attr('readonly', 'readonly');
		// $(".readonly").find('input, textarea, select').attr("disabled", true);

</script>
</body>
</html>

templates/survey/confirm.html
{% extends 'survey/base.html' %}

{% block body_block %}

<h1>Thank You for your feedback</h1>

{% endblock %}

templates/survey/home.html
{% extends 'survey/base.html' %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="col-xs-12">
    <div class="panel panel-default">
  <div class="panel-body">Welcome to Survey Managemnet</div>

</div>

<div class="card col-xs-4">
    <a href="/admin">

<img src="/static/img/admin.png">
    </a>

  </div>
<div class="col-xs-3"><div></div></div>
    <div class="card col-xs-6">
         <a href="{% url 'survey:login' %}">
<img src="/static/img/user.png">
         </a>

  </div>



</div>
</body>
{% endblock %}
</html>

templates/survey/index.html
{% extends "survey/base.html" %}
{% block body_block %}

    <div class="col-xs-12">
  <div class="jumbotron">
    <h2>Welcome To Survey Management System</h2>
    {% if user.is_authenticated %}
        <h4 >Hello {{ user.username }}</h4>
        <li><a href="{% url 'survey:survey_detail' %}" >Surveys</a></li>

    {% else %}
        <h3>Please Login..!!!</h3>
    {% endif %}
  </div>
        </div>

{% endblock %}

templates/survey/login.html
{% extends 'survey/base.html' %}
{% block body_block %}

<body>
  <div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title text-center">Sign In</h5>
            <form class="form-signin" method="post" action="{% url 'survey:user_login' %}">
              {% csrf_token %}
              <div class="form-label-group">
                <input type="text" id="inputUsername" class="form-control" name="username" placeholder="" required autofocus>
                <label for="inputUsername">Username</label>
              </div>

              <div class="form-label-group">
                <input type="password" id="inputPassword" name="password" class="form-control" placeholder="" required>
                <label for="inputPassword">Password</label>
              </div>
              <input type="submit" value="Sign in" class="btn btn-lg btn-primary btn-block text-uppercase">
              <!--<button class="btn btn-lg btn-primary btn-block text-uppercase" type="submit" value="login">Sign in</button>-->
              <hr class="my-4">

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

      <!--<div class="row">-->
            <!--<div class="col-md-offset-3 col-md-3">-->
                <!--<form method="post" action="{% url 'survey:user_login' %}">-->
                    <!--{% csrf_token %}-->
                    <!--{# A more "HTML" way of creating the login form#}-->
                    <!--<div class="login">-->
                <!--<h3>Login </h3>-->
                        <!--<label>Username</label>-->
                <!--<input type="text" id="username" class="form-control input-sm chat-input" name="username"-->
                       <!--placeholder="username" />-->
                <!--</br>-->
                        <!--<label>Password</label>-->
                <!--<input type="password" id="password" class="form-control input-sm chat-input"  name="password"-->
                       <!--placeholder="password" />-->
                <!--</br>-->
                <!--<div class="wrapper" align="center">-->
                <!--<span class="group-btn">-->
                    <!--<input type="submit" class="btn btn-info" name="" value="Login">-->
                <!--</span>-->
                <!--</div>-->
                <!--</div>-->
                <!--</form>-->
            <!--</div>-->
        <!--</div>-->
    </div>
</div>
</body>

{% endblock %}

templates/survey/registration.html
{% extends "survey/base.html" %}
{% load staticfiles %}
{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      {% if registered %}
        <h1>Registration Done Successfully..!!!</h1>
      {% else %}
        <h2>Register Here</h2>
        <h3>Please fill the Details..!!!</h3>
        <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}

templates/survey/survey.html
{% extends 'survey/base.html' %}
{% load survey_extras %}

{% block body_block %}
<div class="container">
	<h2 style="color:#000080">{{user}} welcome back! </h2>
	<h4>About {{survey.name|title}} </h4>
	<div class="survey-description">
		{{survey.description|safe}}
	</div>

	<div class="card">
		<div class="card-header"></div>
		<div class="card-body">
			<form action="/survey/my_surveys/{{survey.id}}/" method="POST">{% csrf_token %}
				<div class="category-container">
					<h3 class="collapsible" id="response_metadata">Response Metadata<span></span></h3>
					<div class="field-wrapper question-required readonly">
						{{ response_form.interviewer.errors }}
						<span class="asterix"> * </span>{{ response_form.user.label_tag }}
						<span class="form-help-text">{{ response_form.user.help_text}}</span>
						<div class="form-field-body">
							{{ response_form.user }}
						</div>
					</div>
					<div class="field-wrapper">
						{{ response_form.conditions.errors }}
						{{ response_form.conditions.label_tag }}
						<span class="form-help-text">{{ response_form.conditions.help_text}}</span>
						<div class="form-field-body">
							{{ response_form.conditions }}
						</div>
					</div>

					<div class="field-wrapper">
						{{ response_form.comments.errors }}
						{{ response_form.comments.label_tag }}
						<span class="form-help-text">{{ response_form.comments.help_text}}</span>
						<div class="form-field-body">
							{{ response_form.comments }}
						</div>
					</div>
				</div>

				<ol class="survey-questions">
				{% for category in categories %}
					<h3 class="collapsible">{{category|title}} Questions<span></span></h3>
					<div class="category-container">
					{% for field in response_form %}
						{% if field.field.widget.attrs.category == category %}
							<li class="q-item" value="{% counter %}">
								{% if field.field.required %}
								<div class="field-wrapper question-required">
									{{ field.errors }}
									<span class="asterix"> * </span><label class="label-inline">{{ field.label }}</label>
								</div>
								{% else %}
								<div class="field-wrapper">
									{{ field.errors }}
									<label class="label-inline">{{ field.label }}</label>
								{% endif %}
									<span class="form-help-text">{{ field.help_text}}</span>
									<div class="form-field-body">
										{{ field }}
									</div>
								</div>
							</li>
						{% endif %}
					{% endfor %}
					</div>
				{% endfor %}
				</ol>

				<div class="submit-button">
					<input type="submit" class="btn btn-success btn-md" name="save_btn" value="Save">
					<input type="submit" class="btn btn-success btn-md" name="finish_btn" value="Finish">
				</div>
			</form>
		</div>
	</div>

	{% endblock %}

	{% block extra_js %}
		<script src="/media/js/jquery.collapsible.js"></script>
		<script type="text/javascript">
			$(document).ready(function() {
				//collapsible management
				$('.collapsible').collapsible({defaultOpen: 'response_metadata'});
			});
		</script>
	{% endblock %}
</div>

templates/survey/survey_home.html
{% extends "survey/base.html" %}
{% block body_block %}
<h2 style="color:#000080">Welcome to Employee Survey System!</h2>
{% if UsersSurveys %}
    <ol>
      {% for survey in UsersSurveys %}
      <h4>
          <li>
            <a href="{{survey.survey_id}}">{{survey.survey.name}}</a>
          </li>
      </h4>
      {% endfor %}
    </ol>
{% else %}
      <p style="color:#ff0000">Sorry..!!! No Surveys Assign</p>
{% endif %}
{% endblock %}